"""
Xntion benchmark package.
This package contains the code for creating and running the Xntion benchmark.
"""

from .constantpath import (
    PROJECT_ROOT,
    CURRENT_DIR,
    DATA_DIR,
    XNATION_DATA_DIR,
    XNATION_KEYWORDS_DIR,
    XNATION_SOURCES_DIR,
    XNATION_SCRAPED_DIR,
    XNATION_BENCHMARK_DIR,
    XNATION_FINAL_BENCHMARK_DIR,
    XNATION_TEXT_PATH,
    XNATION_REPLACEMENT_DESCRIPTION_PATH,
    XNATION_GENERATIONS_PATH,
    XNATION_EXTRACTIONS_PATH,
    XNATION_STATISTICS_PATH,
    XNATION_DISPARITY_PATH
)

__all__ = [
    'PROJECT_ROOT',
    'CURRENT_DIR',
    'DATA_DIR',
    'XNATION_DATA_DIR',
    'XNATION_KEYWORDS_DIR',
    'XNATION_SOURCES_DIR',
    'XNATION_SCRAPED_DIR',
    'XNATION_BENCHMARK_DIR',
    'XNATION_FINAL_BENCHMARK_DIR',
    'XNATION_TEXT_PATH',
    'XNATION_REPLACEMENT_DESCRIPTION_PATH',
    'XNATION_GENERATIONS_PATH',
    'XNATION_EXTRACTIONS_PATH',
    'XNATION_STATISTICS_PATH',
    'XNATION_DISPARITY_PATH'
] 