name: Python Testing

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Set up Python environment
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    # Install Poetry
    - name: Install Poetry
      run: |
        python -m pip install --upgrade pip
        pip install poetry

    # Install dependencies and pytest explicitly
    - name: Install dependencies
      run: |
        poetry install
        python -m pip install pytest pytest-cov

    # Set PYTHONPATH
    - name: Set PYTHONPATH
      run: |
        export PYTHONPATH=$PYTHONPATH:$(pwd)

    # Run tests
    - name: Run tests
      run: |
        pytest --cov=saged --cov-report=xml