name: Python Testing

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Set up Python environment
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    # Install Poetry
    - name: Install Poetry
      run: |
        python -m pip install --upgrade pip
        pip install poetry pytest pytest-cov

    # Install dependencies with Poetry
    - name: Install dependencies
      run: |
        poetry install

    # Set PYTHONPATH
    - name: Set PYTHONPATH
      run: |
        export PYTHONPATH=$PYTHONPATH:$(pwd)

    # Debug: Show Python path
    - name: Show Python Path
      run: |
        python -c "import sys; print(sys.path)"

    # Debug: List installed packages
    - name: List installed packages
      run: |
        poetry show

    # Run tests
    - name: Run tests
      run: |
        poetry run pytest --cov=saged --cov-report=xml