name: Python Testing

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Set up Python environment
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

      # Set PYTHONPATH explicitly in Hatch environment
    - name: Set PYTHONPATH
      run: |
        echo 'PYTHONPATH=$PYTHONPATH:$(pwd)' >> hatch.env

    # Install Hatch
    - name: Install Hatch
      run: |
        python -m pip install --upgrade pip
        pip install hatch

    # Create and update the Hatch environment
    - name: Create Hatch Environment
      run: |
        hatch env create

    # Debug: List installed packages
    - name: List installed packages
      run: |
        hatch run pip list

    

    # Debug: Show Python Path
    - name: Show Python Path
      run: |
        hatch run python -c "import sys; print(sys.path)"

    # Run tests
    - name: Run tests
      run: |
        hatch run test