name: Python Testing

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      # Install uv
      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          version: "latest"

      # Set up virtual environment and install dependencies
      - name: Set up environment
        run: |
          uv venv --python 3.10
          uv sync

      # Run tests
      - name: Run tests
        run: |
          uv run pytest tests/ --cov=saged --cov-report=xml

      # Upload coverage to Codecov (optional)
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          file: ./coverage.xml
          fail_ci_if_error: false
